export default {leftArrow: require('../../assets/images/leftArrow.png'),
rightArrow: require('../../assets/images/rightarrow.png'),
camera: require('../../assets/images/camera.png'),
bgImg:require('../../assets/images/bg1.png'),
bgImg2:require('../../assets/images/bg2.jpg'),
logout:require('../../assets/images/logout.png'),
bg3:require('../../assets/images/bg3.jpg'),
 bg4:require('../../assets/images/bg4.jpg'),
 cart:require('../../assets/images/cart.png'),
imgBg:require('../../assets/images/imgBg.jpg'),
home:require('../../assets/images/home.png'),
profile:require('../../assets/images/profile.png'),
heart:require('../../assets/images/heart.png'),
facebookImage:require('../../assets/images/ic_facebook.png'),
googleImage:require('../../assets/images/ic_google.png'),
menu:require('../../assets/images/menu.png'),
loc:require('../../assets/images/loc.png'),
tick:require('../../assets/images/tick.png'),
cross:require('../../assets/images/cross.png'),
ic_heart:require('../../assets/images/heart2.png'),
ic_share:require('../../assets/images/ic-share.png'),
ic_commet:require('../../assets/images/ic_commet.png'),
ic_search:require('../../assets/images/ic_search.png'),
bg5:require('../../assets/images/bg5.jpg'),
bg6:require('../../assets/images/bg5.png'),
mypic:require('../../assets/images/mypicc.jpg'),
ic_Qr:require('../../assets/images/Qr_logo.png'),
ic_send:require('../../assets/images/ic_send.png')
}